export const reducerCases = {
    SET_USER_INFO: "SET_USER_INFO",
    SET_NEW_USER: "SET_NEW_USER",
    SET_CONTACTS_PAGE: "SET_CONTACTS_PAGE",
    CHANGE_CURRENT_CHAT: "CHANGE_CURRENT_CHAT",
    SET_MESSAGES: "SET_MESSAGES",
    SET_SOCKET: "SET_SOCKET",
    ADD_MESSAGE: "ADD_MESSAGE",
    SET_MESSAGE_SEARCH: "SET_MESSAGE_SEARCH",
}